INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (1, 1, 'Theme', 'Dark Mode');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (2, 2, 'Language', 'English');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (3, 3, 'Notification', 'On');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (4, 4, 'Theme', 'Light Mode');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (5, 5, 'Language', 'Spanish');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (6, 6, 'Notification', 'Off');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (7, 7, 'Theme', 'Dark Mode');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (8, 8, 'Language', 'French');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (9, 9, 'Notification', 'On');
INSERT INTO User_Preferences (preference_id, user_id, category, value) VALUES (10, 10, 'Theme', 'Light Mode');
